spring:
  application:
    name: api-core
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      service: api-core
      env: ${SPRING_ENV:dev}
      region: ap-northeast-2
    distribution:
      percentiles-histogram:
        http.server.requests: true