spring:
  application:
    name: api-public-read
  profiles:
    active: local

server:
  servlet:
    context-path: /api/public

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      service: api-public-read
      env: ${SPRING_ENV:dev}
      region: seoul
    distribution:
      percentiles-histogram:
        http.server.requests: true